name: 'Register Build'
description: 'Register a build for use with dot.Deploy. See the documentation for more information.'
inputs:
  build-id:
    description: 'The build id to register'
    required: true
outputs:
  build-id:
    description: "Outputs the same build id that was input"
  artifact-id:
    description: "Outputs the artifact id where the build id is stored"
  artifact-url:
    description: "Outputs the artifact url where the build id is stored"
runs:
  using: node20
  main: "dist/main.js"
  post: "dist/post.js"
  pre: "dist/pre.js"
