name: 'Register Build'
description: |
  Register a build for use with dot.Deploy. See the documentation for more information.
  This action to be placed at any point in your workflow. It uses pre-processing and post-processing to make sure that
  the build version is registered correctly. This action will upload an artifact named "dot-deploy" to the GitHub artifact store.
inputs:
  version:
    description: |
      The build version is a unique identifier that is used to reference a build. When deploying, the version is used to specify which build to deploy.
      If your build produces more than one artifact, you have to devise a way to link them all to the same build version. This could be, for example, by
      uploading a JSON file that lists the linked artifacts.
      
      You can use the special value "auto" to have the action generate a build version for you. This is useful if you don't want to bother with generating
      a version yourself.
    required: true
outputs:
  version:
    description: "Outputs the build version that was registered"
runs:
  using: node20
  main: "dist/main/index.js"
  post: "dist/post/index.js"
  pre: "dist/pre/index.js"
