name: 'Register Build'
description: 'Register a build for use with dot.Deploy. See the documentation for more information.'
inputs:
  build-id:
    description: 'The build id to register'
    required: true
outputs:
  build-id:
    description: "Outputs the same build id that was input"
    value: ${{ steps.register-build.outputs.build-id }}
  artifact-id:
    description: "Outputs the artifact id where the build id is stored"
    value: ${{ steps.upload-artifact.outputs.artifact-id }}
  artifact-url:
    description: "Outputs the artifact url where the build id is stored"
    value: ${{ steps.upload-artifact.outputs.artifact-url }}
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Create the build-id artifact
      id: register-build
      shell: bash
      run: register-build.sh ${{ inputs.build-id }}

    - name: Upload build-id artifact
      uses: actions/upload-artifact@v4
      id: upload-artifact
      with:
        name: dot-deploy-build-id
        path: ${{ steps.register-build.outputs.build-id-file }}
        if-no-files-found: error
        overwrite: true
        include-hidden-files: true
        compression-level: '0'
