name: 'Register Build'
description: 'Register a build for use with dot.Deploy. See the documentation for more information.'
inputs:
  build-id:
    description: 'The build id to register'
    required: true
outputs:
  build-id:
    description: "Outputs the same build id that was input"
    value: ${{ steps.register-build.outputs.build-id }}
  artifact-id:
    description: "Outputs the artifact id where the build id is stored"
    value: ${{ steps.register-build.outputs.artifact-id }}
runs:
  using: "composite"
  steps:
    - name: Create the build-id artifact
      id: register-build
      shell: bash
      run: |
        # Check that the build-id is at least one character long and contains no spaces or newlines
        if [[ ! "${{ inputs.build-id }}" =~ ^[[:print:]]+$ || "${{ inputs.build-id }}" =~ [[:space:]] || -z "${{ inputs.build-id }}" ]]; then
          echo "Build ID must be at least one character long and contain no spaces, newlines, or control characters" >&2
          exit 1
        fi
        
        # Create a file with the build ID
        echo "${{ inputs.build-id }}" > .dot-deploy-build-id.txt

    - name: Upload build-id artifact
      uses: actions/upload-artifact@v4
      with:
        name: dot-deploy-build-id
        path: .dot-deploy-build-id.txt
